# Generated by Django 5.0 on 2023-12-20 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('coords', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='cinema_image/main_images/contacts/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('seo_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=5000)),
                ('conditions', models.TextField(max_length=5000)),
                ('logo', models.ImageField(blank=True, upload_to='cinema_image/main_images/%Y/%m/%d/')),
                ('top_banner', models.ImageField(blank=True, upload_to='cinema_image/main_images/%Y/%m/%d/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemacity')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=1)),
                ('desc', models.TextField(max_length=5000)),
                ('scheme', models.ImageField(blank=True, upload_to='cinema_image/main_images/cinema_hall/%Y/%m/%d')),
                ('top_banner', models.ImageField(blank=True, upload_to='cinema_image/main_images/cinema_hall/%Y/%m/%d')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='cinema_image/gallery/%Y/%m/%d/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('desc', models.TextField(max_length=5000)),
                ('main_image', models.ImageField(blank=True, upload_to='cinema_image/main_images/movie/%Y/%m/%d/')),
                ('trailer_url', models.CharField(max_length=1000)),
                ('url', models.SlugField(max_length=250)),
                ('budget', models.IntegerField(default=0)),
                ('age', models.PositiveSmallIntegerField(default=16)),
                ('time', models.PositiveSmallIntegerField(default=120)),
                ('melodist', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('screenwriter', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
                ('genre', models.ManyToManyField(blank=True, null=True, to='cinema.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('type', models.CharField(choices=[('3D', '3D'), ('2D', '2D'), ('IMAX', 'IMAX')], default='3D', max_length=6)),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.moviecard')),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=5000)),
                ('main_image', models.ImageField(blank=True, upload_to='cinema_image/main_images/news_events/%Y/%m/%d/')),
                ('url', models.CharField(max_length=512)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('NEWS', 'News'), ('EVENTS', 'Events')], default='NEWS', max_length=6)),
                ('date', models.DateField()),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('main_image', models.ImageField(blank=True, upload_to='cinema_image/main_images/pages/%Y/%m/%d/')),
                ('type', models.CharField(choices=[('VIP', 'Vip'), ('CHILD', 'Child'), ('ADS', 'Ads')], default='VIP', max_length=5)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cinema.movieses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movieses',
            name='reserved_seats',
            field=models.ManyToManyField(blank=True, null=True, to='cinema.reservation'),
        ),
    ]
