# Generated by Django 5.0 on 2024-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_seoblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cinema_image/main_images/banner/%Y/%m/%d/')),
                ('url', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('rotation_speed', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('TOP', 'Top banner'), ('MAIN_NEWS', 'Main news')], default='TOP', max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
