# Generated by Django 5.0 on 2024-01-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_remove_banner_rotation_speed_remove_banner_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
        ),
    ]
