# Generated by Django 5.0 on 2024-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_cinema_seo_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='cinema_image/gallery/%Y/%m/%d/'),
        ),
    ]
