# Generated by Django 5.0 on 2024-01-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_galleryimage_id_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
        ),
    ]
