# Generated by Django 5.0 on 2024-01-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_cinemahall_seo_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
        ),
    ]
