# Generated by Django 5.0 on 2024-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_pages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.BooleanField(choices=[('on', 'ВКЛ'), ('off', 'ВЫКЛ')], default=True),
        ),
    ]
