# Generated by Django 5.0 on 2024-01-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_alter_pages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='type',
            field=models.CharField(choices=[('VIP', 'Vip'), ('CHILD', 'Child'), ('ADS', 'Ads'), ('CINEMA', 'About Cinema')], default='VIP', max_length=10),
        ),
    ]
