# Generated by Django 5.0 on 2024-01-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_alter_pages_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='seo_block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
            preserve_default=False,
        ),
    ]
