# Generated by Django 5.0 on 2024-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_contacts_address_mainpage_seo_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
