# Generated by Django 5.0 on 2024-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_pages_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
