# Generated by Django 5.0 on 2024-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_mainpage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
