# Generated by Django 5.0 on 2024-03-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_moviecard_seo_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecard',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
