# Generated by Django 5.0 on 2024-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_alter_moviecard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecard',
            name='data',
            field=models.DateField(),
        ),
    ]
