# Generated by Django 5.0 on 2024-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_alter_moviecard_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('JUST', 'Just')], default='PHOTO', max_length=5)),
                ('image', models.ImageField(upload_to='cinema_image/main_images/background_banner/%Y/%m/%d/')),
            ],
        ),
    ]
