# Generated by Django 5.0 on 2024-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0030_cinema_conditions_en_cinema_conditions_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemahall",
            name="desc_en",
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="cinemahall",
            name="desc_uk",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
