# Generated by Django 5.0 on 2024-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0031_cinemahall_desc_en_cinemahall_desc_uk"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsevents",
            name="desc_en",
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="newsevents",
            name="desc_uk",
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="newsevents",
            name="title_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="newsevents",
            name="title_uk",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
