# Generated by Django 5.0 on 2024-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0032_newsevents_desc_en_newsevents_desc_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="seo_text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="seo_text_uk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="status_en",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="status_uk",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="title_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="title_uk",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
