# Generated by Django 5.0 on 2024-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0033_mainpage_seo_text_en_mainpage_seo_text_uk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pages",
            name="status_en",
        ),
        migrations.RemoveField(
            model_name="pages",
            name="status_uk",
        ),
        migrations.AddField(
            model_name="pages",
            name="desc_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="desc_uk",
            field=models.TextField(null=True),
        ),
    ]
