# Generated by Django 5.0 on 2024-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0034_remove_pages_status_en_remove_pages_status_uk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pages",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="pages",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pages",
            name="title_uk",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
